### PR TITLE
Fix bus stop icon on map

### PR DESCRIPTION
**Pull request by Beck-berry**
## Changes
* fixed issue about not disappearing bus station icons on map (function was misplaced)

## Backlog
* change icon on different zoom levels - as text should be readable or removed

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
There are test failures.

**Comment by leonardehrenfried** [comment]
Please treat this with the highest priority.

**Comment by leonardehrenfried** [comment]
I think the icon code is missing: i merged it to master but then removed it again.

Try rebasing onto master and then reverting the commit that removed it.

**Comment by leonardehrenfried** [comment]
I'm going to take the liberty to clean this up.

**Comment by leonardehrenfried** [comment]
This somehow contains all the commits that were recently merged from upstream.

Can you start again with a fresh branch and cherry pick your commits?

**Comment by leonardehrenfried** [comment]
Also please squash it into a single commit so it's easier to revert.

**Comment by Beck-berry** [comment]
New PR #168

**Pull request closed without merging**
