### PR TITLE
Merge upstream/master

### LINKED ISSUE #145: Merge all the latest changes from upstream
We have not rebased or merged the changes from upstream (HSLdev/digitransit-ui) for a while but we should not divert too much.

Please merge all the recent changes, resolve the conflicts and then test the application thoroughly.

### PR DESCRIPTION
**Pull request by meromisi**
_**works with node v10.19.0**_

- merged with upstream/master
- added husky hooks (commit-msg, pre-commit, pre-push)
- test coverage and lint are passed without any error

git commands: 
- git merge upstream/master
- solved merge conflicts, and committed the changes

closes #145

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This looks really great but I noticed a few problems:

- https://travis-ci.org/github/mfdz/digitransit-ui/jobs/681053396 The flow tests fail. At the moment I'm leaning towards disabling these tests in our installation but would like to hear your opinion.
- When I click on the search bar to start a route search, the app crashes.

**Comment by leonardehrenfried** [comment]
Can you also document how you went about doing the

**Comment by meromisi** [comment]
It's in the description, btw I asked Beki to test the app and she noticed similar issues with the search box, the problem is I don't get errors at all it works just fine on my setup, I couldn't make the app crash in any way yet.

**Comment by leonardehrenfried** [comment]
I'm running node 12 not 10. That could be the reason.

What are you running?

**Comment by meromisi** [comment]
v10.19.0 (same as HSL)

**Comment by leonardehrenfried** [comment]
I will give this a go later.

**Comment by leonardehrenfried** [comment]
I figured out what the problem was. It seems that the new version cannot read some of the favourites and previous searches of the old version saved in local storage.

**Comment by leonardehrenfried** [comment]
Can you disable the flow tests in `travis.yml`?

**Pull request merged**
