### PR TITLE
Fix cycling factors

### LINKED ISSUE #151: Clean up bicycle safety factors
In https://github.com/mfdz/digitransit-ui/commit/c734d62d84f8be2c55beaffc950dc14e3bc62140 I had to duplicate the settings for the bicycle safety factors because it seems that digitransit doesn't expect those values to be set in `config.hb.json`.

If you remove the stuff inside `triangle:{}` then the default setting does not work when you don't change anything.

If you remove the ones from one level up, then switching from "Avoid elevation changes" back to "Default settings" doesn't work as then there no more cycling factors to be sent to the server and it returns a 500.

On top of this, when you switch from "Avoid elevation changes" to "Default settings" then an extra `triangle=[object+Object]` is put into the URL, which should not be there.

To make matters worse, the server expects the bike factors to be inside a `triangle` object but in the URL they are top level parameters.

Screenshot from 2020-04-23 14-49-30

It it's all very muddled. :man_shrugging: 

Acceptance criteria:

- Make it less of a mess, please. :)

### PR DESCRIPTION
**Pull request by Beck-berry**
If everything's right, all we had to do was to add default values in the `config.default` file for the triangle factors.
Closes #151

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
I tried this and when I tried a route search like this: http://localhost:8080/reiseplan/Erhardtstra%C3%9Fe%2039%2C%2071083%20Herrenberg%3A%3A48.591908948143676%2C8.864893913269045/Richard-Strau%C3%9F-Weg%2C%2071083%20Herrenberg%3A%3A48.593504218318024%2C8.878208398818972?mapMode=bicycle&modes=BICYCLE&time=1587726223

Then there are no triangle factors sent to the server causing the search to fail.

**Comment by Beck-berry** [comment]
Thing is, I found out that after switching back to 'default' the triangle factors were not replaced in the query, so I fixed that - this means after switch to 'default' the values are read from the defaultSettings. (This way no extra `triangle=[object+Object]` goes to the URL.)

Although this does not solve the problem of the start. Interesting, that I do not have the problem you described since I modified the triangle factors through the admin panel (and those values are sent first, not the defaultSettings from the config, I tried out different combinations). These settings are handled by the `localStorage.js` so we might should check what happens if we change the values. 'Local storage' says to me that is should be contained on the client side, but this admin panel is not advertised for the users, so how should they know how to set these values..? :thinking: You might want to check out the `AdminForm.js` too since I feel a bit lost on how to proceed with this right now.

**Comment by Beck-berry** [comment]
Ok, so I dig some more and finally set a the default values on component first mount. This solution worked fine for me but please check on it.
I'll squash the commits if you find it good enough.

**Comment by leonardehrenfried** [comment]
Ok, will check it. BTW, with the squashing I meant #150 .

**Comment by Beck-berry** [comment]
I know, but there were some reverts in this branch and they don't look very nice :sweat_smile:

**Comment by leonardehrenfried** [comment]
Good work!

There is one issue though (I don't think you introduced it): when I select "Default settings" first and then go to "Prefer cycleways" no request is sent to the server. If I then change one of the locations a route is requested with the settings `optimize=GREENWAYS`.

What we want is "Prefer cycleways" requests a route with: 

```
optimize:TRIANGLE
slopeFactor: 0.15
safetyFactor: 0.7
timeFactor: 0.15
```

**Comment by Beck-berry** [comment]
> when I select "Default settings" first and then go to "Prefer cycleways" no request is sent to the server. 

I don't get this one. After starting with default and then choose "Prefer cycleways" there is a new request, only with the GREENWAYS optimization.
Screenshot_2020-04-29_11-22-51
What could I do differently?

Otherwise I'll check how to change the optimize property for this option.

**Comment by leonardehrenfried** [comment]
Yes, please change the values for "Prefer cycleways".

**Comment by Beck-berry** [comment]
Shall we have an option for eg. "Prefer greenways" too or skip that totally? Since now this is the function connected to the "Prefer cycleways" option.

**Comment by leonardehrenfried** [comment]
No, that mode is too confusing (I myself don't understand what it is doing). Prefer cycleways should set the following settings:

```
optimize:TRIANGLE
slopeFactor: 0.15
safetyFactor: 0.7
timeFactor: 0.15
```

**Comment by Beck-berry** [comment]
Ok, done. However I find the function names a bit misleading since this won't set the optimization to `GREENWAYS`... But this was the least manipulation I could reach the goal with.

**Comment by leonardehrenfried** [comment]
Not super-nice but ok.

**Comment by leonardehrenfried** [comment]
There are test failures.

**Pull request merged**
