### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by Beck-berry**
Updated geojson files of layers with new icons.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
I've tested this PR and it looks good.

However, I'm wondering how hard it is to add newlines to the geojson as some of the popups can be quite unreadable:

Screenshot from 2020-02-11 11-38-02

**Comment by leonardehrenfried** [comment]
Also, if I select P&R I see a lot of parking lots.

Screenshot from 2020-02-11 11-41-52

Is this to be expected?

**Comment by Beck-berry** [comment]
New lines in the popup:
Sadly the popup is unable to understand html. We tried to use <br> and also link tags but it did not work. However a simple \n might do the trick, haven't tried it yet.

Many P+Rs: the problem was with the overpass query - now it is updated :)

**Comment by leonardehrenfried** [comment]
OK. P+R looks much better. Thanks!

@hbruch This can be merged. I don't have the permissions myself.

@Beck-berry If you can try out \n that'd be lovely. If not in this PR then in another one.

**Pull request merged**
