### PR TITLE
Endpoints #80

### PR DESCRIPTION
**Pull request by meromisi**
- switched to german endpoints
 - Changed hard coded endpoints to variables

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This looks great.

@Beck-berry @meromisi would you be interested in extracting the code that uses the contstants throughout the app into a separate PR for https://github.com/HSLdevcom/digitransit-ui

**Comment by meromisi** [comment]
@leonardehrenfried, I created a new branch url-endpoints from upstream/master and cherry-picked the exact commits, yarn test-coverage fails at 3 points, where the test has finnish time zone and we use german one that is one hour less. The yarn lint test has 12 errors for inappropriate imports that was made by hsl, can I still create the PR with these errors too? 
image

**Comment by leonardehrenfried** [comment]
Yes, give it a go. Travis should use the correct time zone.

They will review and tell you if you need to change anything.

**Comment by meromisi** [comment]
okay it's done, although 2 travis test failed out of 3. (´。＿。｀)

**Comment by leonardehrenfried** [comment]
I saw an URL like this `http://localhost:8080/haltestellen/vvs%3Ade%3A08115%3A3235%3A1%3A1/aikataulu` when clicking through the app.

`aikataulu` should be replaced with `fahrplan`. Can you check the app where the string is?

**Comment by leonardehrenfried** [comment]
Same for `http://localhost:8080/haltestellen/vvs%3Ade%3A08115%3A3235%3A1%3A1/hairiot`

`hairiot` should be replaced by `stoerungen`.

**Comment by meromisi** [comment]
Do we have to do further modifications? I think we only left Finnish endpoints where it was necessary like comments, config files, translations.

**Comment by leonardehrenfried** [comment]
Good point. I wanted to get it upstream first, but now that I think about it, it's not necessary.

In your RP to HSLdev can you try switching the require and the import statement and run the flow tool again?

**Pull request merged**
