### PR TITLE
add LoRaWAN layer

### LINKED ISSUE #118: Add new LoRaWan map layer
Please convert the following JSON to GeoJSON and add a static map layer:

```
{
  "LRABB_Herrenberg_01": {
    "gateway_desc": "LRABB_Herrenberg_01",
    "gateway_id": "eui-7276ff000b03241e",
    "latitude": 48.6226392,
    "longitude": 8.8291755
  },
  "LRABB_Herrenberg_02": {
    "gateway_desc": "LRABB_Herrenberg_02",
    "gateway_id": "eui-7276ff000b0323a8",
    "latitude": 48.61351925,
    "longitude": 8.8478541787
  },
  "LRABB_Herrenberg_03": {
    "gateway_desc": "LRABB_Herrenberg_03",
    "gateway_id": "eui-7276ff000b032400",
    "latitude": 48.59177235,
    "longitude": 8.8752811704
  },
  "LRABB_Herrenberg_04": {
    "gateway_desc": "LRABB_Herrenberg_04",
    "gateway_id": "eui-7276ff000b032410",
    "latitude": 48.5834651,
    "longitude": 8.8303055
  },
  "LRABB_schoenbuchturm": {
    "gateway_desc": "LRABB_schoenbuchturm",
    "gateway_id": "eui-7276ff000b032232",
    "latitude": 48.60377519,
    "longitude": 8.90928526
  },
  "gateway_herrenberg_0001": {
    "gateway_desc": "gateway_herrenberg_0001",
    "gateway_id": "eui-7276ff000b030c16",
    "latitude": 48.59764323,
    "longitude": 8.87278152
  },
  "gateway_herrenberg_0002": {
    "gateway_desc": "gateway_herrenberg_0002",
    "gateway_id": "eui-7276ff000b030fca",
    "latitude": 48.59524912,
    "longitude": 8.86913277
  },
  "gateway_herrenberg_0003": {
    "gateway_desc": "gateway_herrenberg_0003",
    "gateway_id": "eui-7276ff000b030895",
    "latitude": 48.59830607,
    "longitude": 8.87569754
  },
  "gateway_herrenberg_0004": {
    "gateway_desc": "gateway_herrenberg_0004",
    "gateway_id": "eui-7276ff000b031199",
    "latitude": 48.59504191,
    "longitude": 8.87086225
  },
  "gateway_herrenberg_0005": {
    "gateway_desc": "gateway_herrenberg_0005",
    "gateway_id": "eui-7276ff0039040124",
    "latitude": 48.5909327,
    "longitude": 8.87758101
  }
}
```
The map marker SVG should be the following: 

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="172.3 -67.1 935 935" enable-background="new 172.3 -67.1 935 935" xml:space="preserve">
<g>
	<path fill="#0D83D0" d="M891,381.9c1.4,17.2-4,33.4-15,45.8c-11.8,13.2-29.4,20.4-49.2,20.4H398.2l0,0c-0.2,0-0.4,0-0.6,0h-0.2H397
		l0,0c-17.4-0.2-33.8-7-46-19.2c-13-12.8-20-30-20.2-48.2l0,0c0-33.8,23-61.2,54.4-66.4c4.2-28.2,28.8-51.2,59.2-56
		c1.8-11.2,7.2-22,15.8-30.8c12.4-12.8,29.2-20,46.4-20c22.2,0,41.6,12,52,30c12.2-43.6,52.2-75.6,99.6-75.6
		c51.8,0,95,38.4,102.2,88.4c26-19.4,60.6-17.6,86.6,6.8l-2.8-2.4c20.8,16.8,28,39.6,27,58.8c-0.6,11.4-4.4,21.4-11.2,29.6
		c6.6,2.2,12,6,17.2,11.2c7.2,7.2,12.2,16.2,13.6,26.2l0,0C890.8,380.9,890.8,381.3,891,381.9C891,381.3,891,381.5,891,381.9z
		 M923.2,220.5c-15.2-20.6-37.8-35.8-62.6-42.2c-5.6-1.2-11.4,2.6-12.6,8c-2.2,5.6,1.4,12.8,7.4,14c25,6.6,46.6,24.2,58,47.4
		c9.4,19,11.8,41.4,6.6,62c-1.4,5.8,2.8,12,8.8,12.8c5.4,1.6,11.4-1.6,13.2-6.8C950.2,283.5,943.2,247.3,923.2,220.5z M851.8,217.3
		c-8.6-1.6-15.2,9-11.4,16.4c1.4,3.2,4.6,5.4,8,6.2c13,3.4,24.4,12.4,30.4,24.4c5.4,10.6,6.6,23,3.6,34.4
		c-1.6,5.8,2.6,12.2,8.6,13.2c5.4,1.6,11.8-1.6,13.4-7.2c5.6-20.4,1.4-43.2-11-60.2C883.4,230.9,868.4,220.5,851.8,217.3z"/>
	<g>
		<g>
			<path fill="#363636" d="M348.8,637.5H338v-47.4h10.8l19,29.6l0,0v-29.6h10.8v47.4h-10.8l-19-29.6l0,0V637.5z"/>
			<path fill="#363636" d="M461.8,599.3h-16.4v9.2H461v9.6h-15.6v9.6h16.4v9.6h-27.2v-47.4h27.2V599.3z"/>
			<path fill="#363636" d="M513.8,589.9h33.4v9.6H536v37.8h-10.8v-37.8H514L513.8,589.9L513.8,589.9z"/>
			<path fill="#363636" d="M629.2,610.9l-7.6,26.6h-12l-13.4-47.4H608l8,32.8h0.2l8.6-32.8h8l8.6,32.8h0.8l8-32.8h12l-13.4,47.4h-12
				L629.2,610.9z"/>
			<path fill="#363636" d="M733.8,589.1c13.2,0,24,10.8,24,24.4c0,14-10.2,24.6-24,24.6c-14.2,0-24-10.8-24-24.6
				S720.6,589.1,733.8,589.1z M733.8,627.7c8.6,0,12.2-7,12.2-14.2c0-6.8-4-14.2-12.2-14.2c-8.4,0-12.2,7-12.2,14.2
				S725,627.7,733.8,627.7z"/>
			<path fill="#363636" d="M828.4,589.9c8.8,0,15.6,4.8,15.6,14.2c0,7-4,12-9.8,13.6l16.4,19.8H837l-14.4-18.8v18.8h-10.8v-47.4
				L828.4,589.9L828.4,589.9z M823.4,611.1c4.2,0,8.8-0.2,8.8-6.4s-4.8-6.4-8.8-6.4h-1.2v12.4h1.2V611.1z"/>
			<path fill="#363636" d="M929.8,637.5l-17.6-20.2v20.2h-10.8v-47.4h10.8v19.6l16.4-19.6h13.2l-19.4,22.4l22,25H929.8L929.8,637.5z
				"/>
		</g>
		<g>
			<path fill="#363636" d="M331,483.7h55.4v15.8h-18.8v63h-18v-63h-18.8L331,483.7L331,483.7z"/>
			<path fill="#363636" d="M414.8,562.7h-18v-79h18v31.6h25.4v-31.6h18v79h-18v-31.8h-25.4V562.7z"/>
			<path fill="#363636" d="M518.6,499.7h-27v15.6h26v15.8h-26v15.8h27.2v15.8h-45.4v-79h45.2V499.7L518.6,499.7z"/>
			<path fill="#363636" d="M553.2,483.7h55.4v15.8h-18.8v63h-18v-63H553L553.2,483.7L553.2,483.7z"/>
			<path fill="#363636" d="M637,562.7h-18v-79h18v31.6h25.4v-31.6h18v79h-18v-31.8H637V562.7z"/>
			<path fill="#363636" d="M713.8,562.7h-18v-79h18V562.7z"/>
			<path fill="#363636" d="M747,562.7h-18v-79h18l31.2,48.8h0.2v-48.8h18v79h-18l-31.2-48.8H747V562.7L747,562.7z"/>
			<path fill="#363636" d="M883,535.5c-4.4,20-21,28.6-36.4,28.6c-21.2,0-38.4-18.4-38.4-40.8c0-22.8,16.4-40.8,38.4-40.8
				c14,0,23.4,5.2,30.4,13.4l-11.8,13c-4.6-7.4-10.6-10-17.6-10c-11,0-20,11-20,24.6c0,13.4,9,24.2,20,24.2
				c8.6,0,17.2-5.6,17.2-15.2h-18v-14h36.4v17H883z"/>
			<path fill="#363636" d="M946.6,489.9l-7.4,14.4c0,0-7.8-5.4-15.8-5.4c-6.2,0-9.2,2.6-9.2,7s7.6,7.6,16.4,11.4
				c8.8,3.6,18.6,11.2,18.6,21.6c0,18.8-14.4,25.4-29.8,25.4c-18.6,0-29.6-10.6-29.6-10.6l9-15.2c0,0,10.6,8.8,19.4,8.8
				c4,0,11.4-0.4,11.4-7.8c0-5.6-8.4-8.4-17.8-13c-9.6-4.6-15-12-15-20.2c0-14.6,13-24.2,25.6-24.2
				C936.4,482.3,946.6,489.9,946.6,489.9z"/>
		</g>
	</g>
</g>
</svg>
```

Please edit the SVG so that the letters at the bottom are gone.

### PR DESCRIPTION
**Pull request by Beck-berry**
## Changes
* checkbox is added to the map layer selector dialog
* geojson file is added
* svg icon is customized and added to the geojson file

Closes #118

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Seems that it's enable by dafault. Is this intended?

**Comment by Beck-berry** [comment]
Nope, this is the default setting when adding a new GeoJson layer.

**Comment by leonardehrenfried** [comment]
And it cannot be switched off?

**Comment by Beck-berry** [comment]
Hope this will do the trick.

**Pull request merged**
