### PR TITLE
Add bus icon to map

### LINKED ISSUE #139: Replace bus sign at high zoom with a logo
A user has said that the red dot look like "no through traffic" sign and we would like to see how it would look like if we used a logo.

Acceptance criteria:

- Replace the white dot with red circle on a high zoom level with the following SVG: https://upload.wikimedia.org/wikipedia/commons/6/6d/Bus-Logo_VVS.svg
- Use your best judgment about what "high" means. We definitely don't want to have a super busy map like this: 

Screenshot_2020-04-16-15-18-02 png

### PR DESCRIPTION
**Pull request by Beck-berry**
## Proposed Changes
* added bus icon
* change to icon on high zoom level (100m)

Closes #139

### CODE REVIEW

**Comment by Beck-berry** [comment]
I rebased on master this is where those new commits came from - however I don't quite get why they cause differences. :thinking:

**Comment by leonardehrenfried** [comment]
Holger is a little busy so I will merge and we will revert if we don't like it.

Can you please squash this into a single commit so it can be easily undone?

git squash -i

**Comment by leonardehrenfried** [comment]
Or maybe rebase onto master again.

**Comment by Beck-berry** [comment]
So d64be76 is the important, bus icon related commit.

**Comment by leonardehrenfried** [comment]
I reworked this branch and should we need to revert this, here is the single commit: https://github.com/mfdz/digitransit-ui/pull/150/commits/d96c39d1ac94adc96b75081f88beefab602aafb9

**Pull request merged**
